=== UzielMarquez/Documento-XML/PartidoDS.dtd
<!ELEMENT LigaBBVAMX (Partido+)>
        <!ELEMENT Partido (Fecha, Equipos, Marcador, Goles)>
        <!ELEMENT Fecha (#PCDATA)>
        <!ELEMENT Equipos (EquipoLocal, EquipoVisitante)>
        <!ELEMENT EquipoLocal (#PCDATA)>
        <!ELEMENT EquipoVisitante (#PCDATA)>
        <!ELEMENT Marcador (#PCDATA)>
        <!ELEMENT Goles (Gol+)>
        <!ELEMENT Gol (Jugador, Minuto)>
        <!ELEMENT Jugador (#PCDATA)>
        <!ELEMENT Minuto (#PCDATA)>

=== UzielMarquez/Documento-XML/PartidoDS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LigaBBVAMX SYSTEM "PartidoDS.dtd">
<LigaBBVAMX>
    <Partido>
        <Fecha>Domingo 24 de sep</Fecha>
        <Equipos>
            <EquipoLocal>Toluca</EquipoLocal>
            <EquipoVisitante>América</EquipoVisitante>
        </Equipos>
        <Marcador> 1-1 </Marcador>
        <Goles>
            <Gol>
                <Jugador>Maximiliano Araujo</Jugador>
                <Minuto>54</Minuto>
            </Gol>
            <Gol>
                <Jugador>Diego Valdés</Jugador>
                <Minuto>25</Minuto>
            </Gol>
        </Goles>
    </Partido>
</LigaBBVAMX>
